version: "3.8"
name: movie-web-app

services:
# PostgreSQL database container
  postgres:
      image: postgres
      restart: always
      container_name: postgres
      environment:
        POSTGRES_USER: ${DB_USER}
        POSTGRES_PASSWORD: ${DB_PASSWORD}
        POSTGRES_DB: ${DB_NAME}
      ports:
        - 5432:5432
      networks:
        - bp-network
  # Backend/NestJS Container
  backend:
      container_name: backend
      build:
        context: ./packages/backend
        dockerfile: Dockerfile.local
      restart: always
      env_file: .env
      volumes:
        - ./packages/backend:/svr/app
        - "./scripts/wait.sh:/wait.sh"
        - /svr/app/node_modules
      networks:
        - bp-network
      ports:
        - "${BACKEND_PORT}:${BACKEND_PORT}"
      depends_on:
        - postgres
      links:
        - postgres
        # Frontend/React container
  frontend:
    container_name: frontend
    build:
      context: ./packages/frontend
      dockerfile: Dockerfile.local
    restart: always
    env_file: .env
    ports:
      - "${FRONTEND_PORT}:${FRONTEND_PORT}"
    volumes:
      - "./packages/frontend/src:/usr/src/app/src"
    networks:
      - bp-network
    command: "npm run dev"
volumes:
  pgdata:

networks:
  bp-network:
    driver: bridge
